import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.city).count<[{ count: number }]>("* as count");
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const citiesToInsert = citiesNewYork.map(cityName => ({ name: cityName }));
  await knex(ETableNames.city).insert(citiesToInsert);
};

const citiesNewYork = [
  "Albany",
  "Buffalo",
  "Rochester",
  "Syracuse",
  "Yonkers",
  "New York City",
  "Utica",
  "Ithaca",
  "Binghamton",
  "Elmira",
  "Saratoga Springs",
  "Poughkeepsie",
  "White Plains",
  "Troy",
  "Niagara Falls",
  "Schenectady",
  "Kingston",
  "New Rochelle",
  "Jamestown",
  "Mount Vernon",
  "Peekskill",
  "Cortland",
  "Auburn",
  "Plattsburgh",
  "Amsterdam",
  "Oswego",
  "Long Beach",
  "Beacon",
  "Batavia",
  "Glen Cove",
  "Dunkirk",
  "Olean",
  "Geneva",
  "Lockport",
  "Watertown",
  "North Tonawanda",
  "Cohoes",
  "Rye",
  "Lackawanna",
  "Mechanicville",
  "Little Falls",
  "Canandaigua",
  "Fulton",
  "Oneonta",
  "Corning",
  "Hornell",
  "Norwich",
  "Elmira Heights",
  "Salamanca",
  "Hudson",
  "Johnstown",
  "Gloversville",
  "Port Jervis",
  "Ogdensburg",
  "Middletown",
  "Newburgh",
  "Oneida",
  "Rome",
  "Herkimer",
  "East Aurora",
  "Endicott",
  "Floral Park",
  "Freeport",
  "Garden City",
  "Hempstead",
  "Kenmore",
  "Lynbrook",
  "Massena",
  "Medina",
  "Mineola",
  "New Paltz",
  "Northport",
  "Patchogue",
  "Penn Yan",
  "Riverhead",
  "Rockville Centre",
  "Saranac Lake",
  "Saugerties",
  "Scarsdale",
  "Seneca Falls",
  "Southampton",
  "Spring Valley",
  "Tarrytown",
  "Tonawanda",
  "Wappingers Falls",
  "Warwick",
  "Webster",
  "Westbury",
  "Williamsville",
  "Woodstock",
  "Yaphank",
  "Yorktown Heights",
  "Nanuet",
  "New Cassel",
  "North Syracuse",
  "Old Bethpage",
  "Orangeburg",
  "Orchard Park",
  "Ossining",
  "Owego"
];
